SESSION_ACTIVE_TIME = 60


print(30)
print(30)
print(30)
print(30)
print(30)
print(30)
print(30)

print(SESSION_ACTIVE_TIME)
print(SESSION_ACTIVE_TIME)
print(SESSION_ACTIVE_TIME)
print(SESSION_ACTIVE_TIME)
print(SESSION_ACTIVE_TIME)
print(SESSION_ACTIVE_TIME)
print(SESSION_ACTIVE_TIME)
